multiCapabilities: [{
    browserName: 'firefox',
    specs: ['claimsoverview/login-manager.spec.js']
}, {
    browserName: 'firefox',
    specs: ['claimsoverview/login-supervisor.spec.js']
}, {
    browserName: 'firefox',
    specs: ['claimsoverview/login-claims-analyst.spec.js']
}, {
    browserName: 'chrome',
    specs: ['claimsoverview/login-manager.spec.js']
}, {
    browserName: 'chrome',
    specs: ['claimsoverview/login-supervisor.spec.js']
}, {
    browserName: 'chrome',
    specs: ['claimsoverview/login-claims-analyst.spec.js']
}, {
    browserName: 'ie',
    specs: ['claimsoverview/login-manager.spec.js']
}, {
    browserName: 'ie',
    specs: ['claimsoverview/login-supervisor.spec.js']
}, {
    browserName: 'ie',
    specs: ['claimsoverview/login-claims-analyst.spec.js']
}]